require("plugins.whichkey")
require("plugins.mason")
require("plugins.nvim-lspconfig")
require("plugins.lazygit")
require("plugins.toggleterm")
require("plugins.tokyonight")
require("plugins.snacks")
